// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: service.proto

package sleep

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type SleepRequest struct {
	Milliseconds int64 `protobuf:"varint,1,opt,name=Milliseconds,proto3" json:"Milliseconds,omitempty"`
}

func (m *SleepRequest) Reset()                    { _ = "STUB: not implemented"; return }
func (*SleepRequest) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*SleepRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *SleepRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SleepRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SleepRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SleepRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SleepRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SleepRequest proto.InternalMessageInfo

func (m *SleepRequest) GetMilliseconds() int64 { _ = "STUB: not implemented"; return 0 }

type SleepResponse struct {
}

func (m *SleepResponse) Reset()                    { _ = "STUB: not implemented"; return }
func (*SleepResponse) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*SleepResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *SleepResponse) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SleepResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SleepResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SleepResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SleepResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SleepResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SleepRequest)(nil), "main.SleepRequest")
	proto.RegisterType((*SleepResponse)(nil), "main.SleepResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53,
	0x32, 0xe2, 0xe2, 0x09, 0xce, 0x49, 0x4d, 0x2d, 0x08, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11,
	0x52, 0xe2, 0xe2, 0xf1, 0xcd, 0xcc, 0xc9, 0xc9, 0x2c, 0x4e, 0x4d, 0xce, 0xcf, 0x4b, 0x29, 0x96,
	0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x42, 0x11, 0x53, 0xe2, 0xe7, 0xe2, 0x85, 0xea, 0x29, 0x2e,
	0xc8, 0xcf, 0x2b, 0x4e, 0x35, 0x72, 0x86, 0x1a, 0x12, 0x0c, 0xb1, 0x40, 0xc8, 0x98, 0x8b, 0x03,
	0xcc, 0x77, 0xcb, 0x2f, 0x12, 0x12, 0xd2, 0x03, 0xd9, 0xa3, 0x87, 0x6c, 0x89, 0x94, 0x30, 0x8a,
	0x18, 0xc4, 0x10, 0x27, 0x93, 0x0b, 0x0f, 0xe5, 0x18, 0x6e, 0x3c, 0x94, 0x63, 0xf8, 0xf0, 0x50,
	0x8e, 0xb1, 0xe1, 0x91, 0x1c, 0xe3, 0x8a, 0x47, 0x72, 0x8c, 0x27, 0x1e, 0xc9, 0x31, 0x5e, 0x78,
	0x24, 0xc7, 0xf8, 0xe0, 0x91, 0x1c, 0xe3, 0x8b, 0x47, 0x72, 0x0c, 0x1f, 0x1e, 0xc9, 0x31, 0x4e,
	0x78, 0x2c, 0xc7, 0x70, 0xe1, 0xb1, 0x1c, 0xc3, 0x8d, 0xc7, 0x72, 0x0c, 0x49, 0x6c, 0x60, 0xcf,
	0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x27, 0xe6, 0xf2, 0x8c, 0xdd, 0x00, 0x00, 0x00,
}

func (this *SleepRequest) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (this *SleepResponse) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (this *SleepRequest) GoString() string { _ = "STUB: not implemented"; return "" }

func (this *SleepResponse) GoString() string { _ = "STUB: not implemented"; return "" }

func valueToGoStringService(v interface{}, typ string) string { _ = "STUB: not implemented"; return "" }

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SleepServiceClient is the client API for SleepService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SleepServiceClient interface {
	SleepFor(ctx context.Context, in *SleepRequest, opts ...grpc.CallOption) (*SleepResponse, error)
}

type sleepServiceClient struct {
	cc *grpc.ClientConn
}

func NewSleepServiceClient(cc *grpc.ClientConn) SleepServiceClient {
	_ = "STUB: not implemented"
	return *new(SleepServiceClient)
}

func (c *sleepServiceClient) SleepFor(ctx context.Context, in *SleepRequest, opts ...grpc.CallOption) (*SleepResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SleepServiceServer is the server API for SleepService service.
type SleepServiceServer interface {
	SleepFor(context.Context, *SleepRequest) (*SleepResponse, error)
}

// UnimplementedSleepServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSleepServiceServer struct {
}

func (*UnimplementedSleepServiceServer) SleepFor(ctx context.Context, req *SleepRequest) (*SleepResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func RegisterSleepServiceServer(s *grpc.Server, srv SleepServiceServer) {
	_ = "STUB: not implemented"
	return
}

func _SleepService_SleepFor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

var _SleepService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.SleepService",
	HandlerType: (*SleepServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SleepFor",
			Handler:    _SleepService_SleepFor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func (m *SleepRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SleepRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SleepRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SleepResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SleepResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SleepResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintService(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *SleepRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SleepResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovService(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozService(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (this *SleepRequest) String() string { _ = "STUB: not implemented"; return "" }

func (this *SleepResponse) String() string { _ = "STUB: not implemented"; return "" }

func valueToStringService(v interface{}) string { _ = "STUB: not implemented"; return "" }

func (m *SleepRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SleepResponse) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipService(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthService = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowService   = fmt.Errorf("proto: integer overflow")
)
